export { Navigation } from './NavigationPage/Navigation'
export { LandingPage } from './LandingPage/LandingPage'
export { ProjectsPage }  from './ProjectsPage/ProjectsPage'
export { SkillsPage }  from './SkillsPage/SkillsPage'
export { ContactPage } from './ContactPage/ContactPage'